spring.application.name=ms-query-library
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/CQRSbase
spring.datasource.username=root
spring.datasource.password=

#show or not log for each sql query
spring.jpa.show-sql=true
#hibernate ddl auto (create , create-drop , update, validate)
spring.jpa.hibernate.ddl-auto=create-drop