spring.application.name=ms-editeur
server.port=8084
spring.datasource.url=jdbc:mysql://localhost:3306/CQRSbase-editeur
spring.datasource.username=root
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

#new property
spring.main.allow-bean-definition-overriding=true